### ISSUE TITLE
сдвиг отмеченного текста вправо с сохранением однострочного комментария в перовой позиции

### ISSUE THREAD

**Issue by majorgleb** [T-Soft/Parser3LanguageSupport#12]
Хочется чтобы при сдвиге вправо по Tab все строки, которые закомментированы # в первой позиции игнорировались и не двигались -- т.е. закомментированная строка чтобы оставалась закомментированной

При сдвиге отмеченного текста влево такой проблемы нет, т.к. закомментированные строки уже "упираются" в левый край и не двигаются по умолчанию

**Comment by TonySkorik** [comment]
Отдельной командой точно можно. 
Существующее поведение TAB менять считаю некорректной идеей : на каждое нажатие будет запускаться код, анализирующий selection на наличие #.

**Comment by majorgleb** [comment]
> Существующее поведение TAB менять считаю некорректной идеей : на каждое нажатие будет запускаться код, анализирующий selection на наличие #.

А почему это нельзя сделать только для парсерных файлов? а в парсерных файлах это как раз очень и нужно. А в остальных файлах этот код работать не будет, т.к. он привязан именно к парсеру

**Comment by TonySkorik** [comment]
Все можно) 
Насколько я понимаю, такое стандартное поведение, как сдвиг выделения по TAB так просто не расширяется. Я поресерчу, что можно с этим сделать.

**Comment by majorgleb** [comment]
С первого раза как хотелось - не взлетело. 

1\ строки с комментарием # - вообще не должны трогаться - сейчас они тоже табуируются при # остающейся на месте

идея с табуированием комментария внутри -- хорошая, особенно при таком варианте:
![image](https://user-images.githubusercontent.com/32306869/51062095-9d871000-1606-11e9-9ae3-acc59c91daad.png)
но когда комментарий нужно оставить неизменным -- это сильно мешает. причем именно второго варианта на мой взгляд больше - т.е. когда комменты вообще трогать никак не надо.

думаю нужно или в конфиг вынести эту настройку (табуировать ли контент комментария) или отключить какое либо изменение строк комментария

2\ см картинку -- несмотря на то что стр 126 не отмечена - она тоже табуируется
![image](https://user-images.githubusercontent.com/32306869/51062007-53059380-1606-11e9-8e32-978d2bf4e5ed.png)
а не должна

**Comment by majorgleb** [comment]
я не правильно начал -- на самом деле "взлетело", но с нюансами :)

**Comment by majorgleb** [comment]
кстати еще один странный эффект с другой стороны

см по экранам:

курсор стоит в левой возиции на 126
![image](https://user-images.githubusercontent.com/32306869/51196121-7dee3100-18ff-11e9-8c9b-040de4348115.png)

нажимаю shift и стрелку вверх -- и так несколько раз:
стр 126 не отмечена и курсора там нет!
![image](https://user-images.githubusercontent.com/32306869/51196164-9d855980-18ff-11e9-97cd-99e905123791.png)

после чего стоя на 101 стр нажимаю TAB и вот что получаю:
![image](https://user-images.githubusercontent.com/32306869/51196211-b4c44700-18ff-11e9-805c-d834cb2445dc.png)

126 стр "поползла"

и если при отменке сверху вниз (что я постоянно практикую) есть еще какая то логика в сдвиге строки на которой стоит курсор в крайне левой позиции, то при отметке блока методом снизуввех -- тут движение строки вне блока логически вообще никак не объяснимо. думаю это какая то граничная проблема +/-1 строки
