### ISSUE TITLE
комментирование с помощью ^rem

### ISSUE THREAD

**Issue by majorgleb** [T-Soft/Parser3LanguageSupport#13]
Хочется, но не горит совсем, чтобы был второй комплект для комментирования -- типа базовый через # как сейчас

И второй через ^rem{...}

возможно такое? (но сдвиг вправо намного  важнее!!! прям супер как важнее)

**Comment by TonySkorik** [comment]
Конечно возможно! Будет отдельная команда типа Rem selection.

**Comment by majorgleb** [comment]
REMing selection :)
