### ISSUE TITLE
comment // ошибка в комментрировании отмеченного куска кода

### ISSUE THREAD

**Issue by majorgleb** [T-Soft/Parser3LanguageSupport#3]
![image](https://user-images.githubusercontent.com/32306869/43363571-32c8667a-9310-11e8-8216-a135f8ac1175.png)

это получилось, когда я нажал CtrlK CtrlC - коммент поставился где-то в середине, вместо первой позхици

**Comment by TonySkorik** [comment]
Added two commands : 
Parser3: Comment selection
Parser3: Uncomment selection
